# v22_mirofish_oasis_profile_schema_guard
# Runtime-only guard for scripts/run_parallel_simulation.py.
# It fixes missing OASIS Twitter profile columns generated by the zero-entity fallback.
# ASCII-only.

import sys

_SAFE_COLUMNS = {
    "user_char", "description", "name", "username", "user_name", "screen_name",
    "user_id", "id", "profile_image_url", "location", "created_at",
    "followers_count", "friends_count", "following_count", "statuses_count",
    "tweet_count", "listed_count", "verified", "protected", "bot", "lang",
}
_NUMERIC_COLUMNS = {
    "user_id", "id", "followers_count", "friends_count", "following_count",
    "statuses_count", "tweet_count", "listed_count",
}
_BOOL_COLUMNS = {"verified", "protected", "bot"}

def _is_parallel_sim_process():
    return "run_parallel_simulation.py" in " ".join(str(x) for x in sys.argv)

def _safe_str(value):
    try:
        if value is None:
            return ""
        if value != value:
            return ""
        return str(value)
    except Exception:
        return ""

def _row_text(row):
    keys = [
        "user_char", "description", "persona", "personality", "bio", "profile",
        "user_profile", "summary", "name", "username", "user_name", "screen_name",
        "id", "user_id",
    ]
    parts = []
    for key in keys:
        try:
            if key in row.index:
                value = _safe_str(row.get(key, "")).strip()
                if value:
                    parts.append(value)
        except Exception:
            pass
    return " | ".join(parts).strip() or "Synthetic fallback agent with neutral behavior and realistic social-media habits."

def _default_series(df, key):
    import pandas as pd
    n = len(df.index)
    if key in _BOOL_COLUMNS:
        return pd.Series([False] * n, index=df.index)
    if key in _NUMERIC_COLUMNS:
        if key in ("id", "user_id"):
            return pd.Series(list(range(100000, 100000 + n)), index=df.index)
        return pd.Series([0] * n, index=df.index)
    if key == "lang":
        return pd.Series(["en"] * n, index=df.index)
    if key == "created_at":
        return pd.Series(["2024-01-01"] * n, index=df.index)
    if key in ("username", "user_name", "screen_name"):
        return pd.Series(["agent_%03d" % i for i in range(n)], index=df.index)
    if key == "name":
        return pd.Series(["Agent %03d" % i for i in range(n)], index=df.index)
    if key in ("description", "user_char"):
        return df.apply(_row_text, axis=1)
    return pd.Series([""] * n, index=df.index)

def _ensure_profile_columns(df):
    try:
        import pandas as pd
        if not isinstance(df, pd.DataFrame):
            return df
        need = ["user_char", "description", "name", "username", "user_id"]
        changed = False
        for key in need:
            if key not in df.columns:
                df = df.copy() if not changed else df
                df[key] = _default_series(df, key)
                changed = True
        for key in ("screen_name", "user_name"):
            if key not in df.columns:
                df = df.copy() if not changed else df
                df[key] = df["username"] if "username" in df.columns else _default_series(df, key)
                changed = True
        return df
    except Exception:
        return df

if _is_parallel_sim_process():
    try:
        import pandas as pd
        _orig_read_csv = pd.read_csv
        _orig_getitem = pd.DataFrame.__getitem__
        def _patched_read_csv(*args, **kwargs):
            df = _orig_read_csv(*args, **kwargs)
            try:
                path = str(args[0]) if args else str(kwargs.get("filepath_or_buffer", ""))
            except Exception:
                path = ""
            low = path.lower()
            if ("twitter" in low) or ("profile" in low) or ("agent" in low):
                df = _ensure_profile_columns(df)
            return df
        def _patched_getitem(self, key):
            if isinstance(key, str) and key in _SAFE_COLUMNS and key not in self.columns:
                try:
                    self[key] = _default_series(self, key)
                except Exception:
                    pass
            return _orig_getitem(self, key)
        pd.read_csv = _patched_read_csv
        pd.DataFrame.__getitem__ = _patched_getitem
        print("[mirofish] v22 OASIS profile schema guard enabled", flush=True)
    except Exception as exc:
        try:
            print("[mirofish] v22 guard failed to enable: %r" % (exc,), flush=True)
        except Exception:
            pass
